config/routes.rb
Rails.application.routes.draw do
  resources :faqs
  root :to => 'faqs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/faq_searchable.rb
module FaqSearchable
  extend ActiveSupport::Concern
  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    # インデックスするフィールドの一覧
    INDEX_FIELDS = %w(staff question answer).freeze
    # インデックス名
    index_name "es_sample_faq_#{Rails.env}"
    # マッピング情報
    settings do
      mappings dynamic: 'false' do # 動的にマッピングを生成しない
        indexes :staff, analyzer: 'kuromoji', type: String
        indexes :question,  analyzer: 'kuromoji', type: String
        indexes :answer,  analyzer: 'kuromoji', type: String
      end
    end
    # インデックスするデータを生成
    # @return [Hash]
    def as_indexed_json(option = {})
      self.as_json.select { |k, _| INDEX_FIELDS.include?(k) }
    end
  end
  module ClassMethods
    # indexの作成メソッド
    def create_index!
      client = __elasticsearch__.client
      client.indices.delete index: self.index_name rescue nil
      client.indices.create(index: self.index_name,
                            body: {
                                settings: self.settings.to_hash,
                                mappings: self.mappings.to_hash
                            })
    end
  end
end

app/models/faq.rb
class Faq < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings index: {
             analysis: {
                 tokenizer: {
                     kuromoji_user_dict: {
                         type: :kuromoji_tokenizer
                     },
                     ngram_tokenizer: {
                         type: 'nGram',
                         min_gram: '2',
                         max_gram: '3',
                         token_chars: ['letter', 'digit']
                     }
                 },
                 filter: {
                     # 指定した品詞を除外する
                     pos_filter: {
                         type: :kuromoji_part_of_speech,
                         stoptags: ['助詞-格助詞-一般', '助詞-終助詞']
                     },
                     greek_lowercase_filter: {
                         type: :lowercase,
                         language: :greek,
                     },
                 },
                 analyzer: {
                     kuromoji_analyzer: {
                         type: :custom,
                         tokenizer: :kuromoji_user_dict,
                         filter: [:kuromoji_baseform, :pos_filter, :greek_lowercase_filter, :cjk_width]
                     },
                     ngram_analyzer: {
                         tokenizer: :ngram_tokenizer,
                         filter: [:cjk_width]
                     }
                 }
             }
         } do
    mapping do
      indexes :staff,
              type: 'string',
              index: :analyzed,
              analyzer: :kuromoji_analyzer
      indexes :question,
              type: 'string',
              index: :analyzed,
              analyzer: :ngram_analyzer
      indexes :answer,
              type: 'string',
              index: :analyzed,
              analyzer: :ngram_analyzer
    end
  end

  Faq.first.__elasticsearch__.update_document
  Faq.import

  #include FaqSearchable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = if params[:search].nil?
              logger.debug('パラメータない')
              Faq.all
            elsif params[:search]
              logger.debug('パラメータある')
              logger.debug(params[:search])
              Faq.search(params[:search]).records
            else
              Faq.all
            end
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'Faq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:staff, :question, :answer)
    end
end

app/controllers/main_controller.rb
# -*- encoding: utf-8 -*-
class MainController < ApplicationController
    def index

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form.html.erb
<%= form_with(model: faq, local: true) do |form| %>
  <% if faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% faq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :staff %>
    <%= form.text_field :staff, id: :faq_staff %>
  </div>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_area :question, id: :faq_question %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_area :answer, id: :faq_answer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing Faq</h1>

<%= render 'form', faq: @faq %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faqs</h1>

<%= form_tag faqs_path, :method => :get do %>
    <%= text_field_tag :search, params[:search], :placeholder => '検索' %>
    <%= submit_tag 'Search', :name => nil %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Staff</th>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faqs.each do |faq| %>
      <tr>
        <td><%= faq.staff %></td>
        <td><%= faq.question %></td>
        <td><%= faq.answer %></td>
        <td><%= link_to 'Show', faq %></td>
        <td><%= link_to 'Edit', edit_faq_path(faq) %></td>
        <td><%= link_to 'Destroy', faq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faq', new_faq_path %>

app/views/faqs/new.html.erb
<h1>New Faq</h1>

<%= render 'form', faq: @faq %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Staff:</strong>
  <%= @faq.staff %>
</p>

<p>
  <strong>Question:</strong>
  <%= @faq.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @faq.answer %>
</p>

<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myservice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<!DOCTYPE html>
<html>
  <head></head>
    <body>
      <p>Hello World!!</p>
    </body>
</html>